---
- name: Install DNS Server on Linux
  hosts: all
  remote_user: vagrant
  gather_facts: true
- ansible.builtin.import_playbook: ./distro/debian.yml
  when: ansible_distribution == 'Debian' 
- ansible.builtin.import_playbook: ./distro/debian_config.yml
  when: ansible_distribution == 'Debian'
- ansible.builtin.import_playbook: ./distro/centos.yml
  when: ansible_distribution == 'CentOS'
- ansible.builtin.import_playbook: ./distro/centos_config.yml
  when: ansible_distribution == 'CentOS'
- ansible.builtin.import_playbook: ./distro/ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- ansible.builtin.import_playbook: ./distro/ubuntu_config.yml
  when: ansible_distribution == 'Ubuntu'
