---
- name: Run Script on Debian 12.2
  hosts: all
  remote_user: vagrant
  gather_facts: true

- ansible.builtin.import_playbook: ./distro/debian12_2.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '12.2'
- ansible.builtin.import_playbook: ./config/debian_config.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '12.2'
