---
- name: Install BIND9, Update APT Package Lists, and Copy Configurations On Ubuntu
  become: true
  hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Update APT Package Lists
      apt:
        update_cache: yes
    - name: Upgrading the system.
      apt:
        upgrade: yes

    - name: Install BIND9, BIND9 Utils, and BIND9 Documentation
      apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
        state: present

